Feature/version 1.1.0
sitmena/apifort-gateway pull request #151
Opened 2023-03-07 21:44 UTC by firas-sitech

code fix

2023-03-11 20:52 UTC, iabughosh requested changes

2023-03-11 20:52 UTC, iabughosh commented on src/main/java/me/sitech/apifort/api/CacheRest.java
> +                .responseMessage().code(ApiFortStatusCode.UNAUTHORIZED).message(ApiFortStatusCode.UNAUTHORIZED_STRING).responseModel(GeneralRes.class).endResponseMessage()
Make sure layout is fine.

2023-03-11 20:52 UTC, iabughosh commented on src/main/java/me/sitech/apifort/api/HealthRest.java
> +    @Override
Why this is created? we already have microprofile health extension.

2023-03-11 20:52 UTC, iabughosh commented on src/main/java/me/sitech/apifort/domain/module/ProfileCounts.java
> +        this.uuid = (String) obj[0];
Do some validations on the argument like null checks and array is not empty.

2023-03-11 20:52 UTC, iabughosh commented on src/main/java/me/sitech/apifort/domain/response/profile/ClientProfileDetailsRes.java
> +    @JsonProperty("public_certificate")
To be confirmed if this is still backward compatible?!

2023-03-11 20:52 UTC, iabughosh commented on src/main/java/me/sitech/apifort/router/v1/client_profile/ClientProfileRouter.java
> +                    if(Util.isNotEmpty(apiKey)){
I would prefer to use early-exit pattern here on apiKey validation..

2023-03-11 20:52 UTC, iabughosh commented on src/main/java/me/sitech/apifort/router/v1/client_profile/ClientProfileRouter.java
> +                    String realm = exchange.getIn().getHeader(ApiFort.API_REALM, String.class);
Same

2023-03-11 20:52 UTC, iabughosh commented on src/main/java/me/sitech/apifort/router/v1/gateway/GatewayRouter.java
> +
Remove extra line,

2023-03-11 20:52 UTC, iabughosh commented on src/main/resources/application.properties
> +#quarkus.flyway.locations=db/migration/ddl,db/migration/delmonte
Remove comment on this please..

2023-03-11 20:52 UTC, iabughosh commented on src/main/resources/db/migration/ddl/V1.0.1__UPDATE__api-fort.sql
> +ALTER TABLE `apifort_client_profile` ADD COLUMN `title` VARCHAR(100) NULL AFTER `uuid`;
No man please, for any DB change please create new file. db migration is an append only directory. Modifying an existing scripts file, an existing projects will not be able to start unless you cleared the out the whole schema.

2023-03-15 09:26 UTC, firas-sitech commented on src/main/java/me/sitech/apifort/api/HealthRest.java
> +    @Override
for check the token it is working fine

2023-03-15 10:29 UTC, firas-sitech commented on src/main/java/me/sitech/apifort/api/CacheRest.java
> +                .responseMessage().code(ApiFortStatusCode.UNAUTHORIZED).message(ApiFortStatusCode.UNAUTHORIZED_STRING).responseModel(GeneralRes.class).endResponseMessage()
this is additional api we could remove it if not need it

2023-03-15 11:03 UTC, firas-sitech commented on src/main/java/me/sitech/apifort/router/v1/client_profile/ClientProfileRouter.java
> +                    if(Util.isNotEmpty(apiKey)){
what do you mean?

2023-03-15 11:04 UTC, firas-sitech commented on src/main/java/me/sitech/apifort/router/v1/gateway/GatewayRouter.java
> +
which line?

2023-03-15 11:18 UTC, closed without merging